### ISSUE TITLE
关于应用的命名空间namespace

### ISSUE THREAD

**Issue by hainuo** [youzan/zan-installer#2]
```
└─<>──» zan                                                         0 < 16:48:59
   __    __
  /\ \  /\ \
  \ `\`\\/'/ ___   __  __  ____      __      ___
   `\ `\ /' / __`\/\ \/\ \/\_ ,`\  /'__`\  /' _ `\
     `\ \ \/\ \L\ \ \ \_\ \/_/  /_/\ \L\.\_/\ \/\ \
       \ \_\ \____/\ \____/ /\____\ \__/.\_\ \_\ \_\
        \/_/\/___/  \/___/  \/____/\/__/\/_/\/_/\/_/
Create a new ZanPhp application.
Which type application would you create? (use <space> to select)
❯ ● HTTP
  ○ TCP
Your application name: (ex: zanphp-demo) jieba
Your application namespace: (ex: zanphp/zanhttp) hainuo/jieba
Please input a output directory: ~/zan
Downloading the source code archive ...
Extracting archive ...
Congratulations, your application has been generated to the following directory.
/Users/fengliu/zan/jieba/
See /Users/fengliu/zan/jieba/README.md for information on how to run.
Composer installing...
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing zanphp/zan (dev-master ebc9cf7)
    Cloning ebc9cf7c05dca5c3f53ec5fde80a7cac15c4aeaa from cache

Writing lock file
Generating autoload files
```

在创建的时候有这样的话 
`Your application namespace: (ex: zanphp/zanhttp) hainuo/jieba`
这里给我的理解是你的应用命名空间是什么
但是实际的命名空间通过代码/zan/jieba/src/Controller/Index/IndexController.php

```
namespace Com\Youzan\ZanHttpDemo\Controller\Index;
```

和composer.json来看

```
    "name": "hainuo/jieba",
.....
    "autoload": {
        "psr-4": {
            "Com\\Youzan\\ZanHttpDemo\\": "src",
            "Com\\Youzan\\ZanHttpDemo\\Tests\\": "test",
            "Com\\Youzan\\ZanHttpDemoInit\\": "init"
        },
        "classmap": []
    },
```

只是定义了名字。
这里是一个 严重不符的地方。

**Comment by agalwood** [comment]
是有概念上的差异，这里的namespace是指你的应用作为composer包的namespace，在你的应用被其他人require的时候的名字区分。

**Comment by hainuo** [comment]
这么说很怪异  因为如果我创建多个http的包  难道psr-0的namespace全为\zanphp\zanhttpdemo这还是有问题  还是觉得包名与命名空间区分开   更让人明白一些
------------------ 原始邮件 ------------------
发件人: "Dr_rOot"notifications@github.com
发送时间: 2016年7月28日(星期四) 晚上10:39
收件人: "youzan/zan-installer"zan-installer@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Author"author@noreply.github.com;
主题: Re: [youzan/zan-installer] 关于应用的命名空间namespace (#2)

是有概念上的差异，这里的namespace是指你的应用作为composer包的namespace，在你的应用被其他人require的时候的名字区分。

&mdash;

**Comment by agalwood** [comment]
嗯，你说的对，我看看怎么改进。
还有我们内部有Zan TCP的版本，所以普遍会有一个HTTP项目依赖TCP包的情况...orz

**Comment by agalwood** [comment]
感谢你提交的issue，我已经修复了，请使用

``` bash
composer global update
```

更新一下 zan-installer 到 v1.0.6 版本

**Comment by hainuo** [comment]
好的  晚上试试  
------------------ 原始邮件 ------------------
发件人: "Dr_rOot"notifications@github.com
发送时间: 2016年7月29日(星期五) 下午3:53
收件人: "youzan/zan-installer"zan-installer@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Author"author@noreply.github.com;
主题: Re: [youzan/zan-installer] 关于应用的命名空间namespace (#2)

感谢你提交的issue，我已经修复了，请使用
 composer global update

更新一下zan-installer

&mdash;

**Comment by hainuo** [comment]
@agal

**Comment by hainuo** [comment]
发现这里已经可以了
