### ISSUE TITLE
关于创建目录的问题

### ISSUE THREAD

**Issue by hainuo** [youzan/zan-installer#3]
我首先在 $home 下创建了一个zan的文件夹，期望文件是创建在这个文件夹里面
# 0x01

第一种情况 命令写的是这个

```
Your application name: (ex: zanphp-demo) test
Please input a output directory: test
```

然后会发现 文件被创建在这里面

```
Congratulations, your application has been generated to the following directory.
/Users/hainuo/zantest/test/
```

我的期望是 `/Users/hainuo/zan/test/`
# 0x02

第二种情况 

```
Your application name: (ex: zanphp-demo) xxx
Please input a output directory: /Users/hainuo/xxx/
```

文件创建 

```
Congratulations, your application has been generated to the following directory.
/Users/hainuo/xxx/xxx/
```

我的期望值是`/Users/hainuo/xxx/`

综上感觉路径设计的不是那么人性化 
我觉得路径设计上如果不是指定绝对路径，那么应该是当前路径+'/'+指定的path  不需要再将 applicationname 加上，如果是有特殊用法，应该在手册或者创建时注明。

**Comment by agalwood** [comment]
你提的两种情况都是你已经创建好项目目录的情况，如果用户没有提前操作，那代码解压出来不带application name就可能坑爹了，好多文件和目录就散落在用户指定的目录了，这样感觉更容易给用户造成困扰：（

当时之所以这么设计是有点偷懒成分，还有个考虑是从github下载的代码压缩包的结构是里面还有一级目录，解压之后的目录操作挪一个文件夹到指定目录比较方便，所以就这么做了。

**Comment by hainuo** [comment]
在home目录下直接执行zan 然后  目录是相对的只填写test  可以通过第一种情况得到真是目录会是 /Users/hainuotest/test  于是bug来了  yzan没有权限在Users目录下建立目录hainuotest 
------------------ 原始邮件 ------------------
发件人: "Dr_rOot"notifications@github.com
发送时间: 2016年7月30日(星期六) 晚上10:34
收件人: "youzan/zan-installer"zan-installer@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Author"author@noreply.github.com;
主题: Re: [youzan/zan-installer] 关于创建目录的问题 (#3)

你提的两种情况都是你已经创建好项目目录的情况，如果用户没有提前操作，那代码解压出来不带application name就可能坑爹了，好多文&#x4EF6;和目录就散落在用户指定的目录了，这样感觉更容易给用户造成困扰：（

当时之所以这么设计是有点偷懒成分，还有个考虑是从github下载的代码压缩包的结构是里面还有一级目录，解压之后的目录操作挪一个文&#x4EF6;夹到指定目录比较方便，所以就这么做了。

&mdash;

**Comment by hainuo** [comment]
@agalwood   application name 这里 就是多格目录这个我倒没什么特别的恩主要是 这个目录生成规则 有问题  你可以再仔细看 我再要求中填写的是 test ，按照猜想应该在我当前的目录 `/Users/hainuo/zan/`下面创建  `/test/applicationname`得到的目录应该是`/Users/hainuo/zan/test/applicationname/`但是程序显然有 bug 创建的是`/Users/hainuo/zantest/test/`  zantest这个目录  肯定是有问题的

**Comment by agalwood** [comment]
好的，感谢反馈，容我再调试调试

**Comment by agalwood** [comment]
@hainuo 非常抱歉，最近太忙，修复晚了，还请升级zan-installer到v1.0.7版本
