### ISSUE TITLE
rename报错文件已经存在

### ISSUE THREAD

**Issue by daxiong123** [youzan/zan-installer#4]
PHP Warning:  rename(/vagrant/zanhttp-boilerplate-master,/vagrant/test/): File exists in /home/vagrant/.composer/vendor/youzan/zan-installer/src/Installer.php on line 286

会先创建项目目录（ getDirectory方法） 再rename 直接警告 无法正常安装

**Comment by agalwood** [comment]
/vagrant/test是你填的目标目录么？还是本来就有的目录？

**Comment by daxiong123** [comment]
目标目录

**Comment by daxiong123** [comment]
Create a new ZanPhp application.
Which type application would you create? (use <space> to select)
❯ ● HTTP
  ○ TCP
Your application name: (ex: zanphp-demo) test
Please input a output directory:  /vagrant
Your composer name: (ex: zanphp/zanhttp)
Use composer name: zanphp/zanhttp
Your application namespace: (ex: Com\Youzan\ZanHttpDemo\) Com\Test
Downloading the source code archive ...
Extracting archive ...
PHP Warning:  rename(/vagrant/zanhttp-boilerplate-master,/vagrant、/vagrant/test/): No such file or directory in /home/vagrant/.composer/vendor/youzan/zan-installer/src/Installer.php on line 286

Warning: rename(/vagrant/zanhttp-boilerplate-master,/vagrant、/vagrant/test/): No such file or directory in /home/vagrant/.composer/vendor/youzan/zan-installer/src/Installer.php on line 286
PHP Warning:  file_get_contents(/vagrant、/vagrant/test/init/app.php): failed to open stream: No such file or directory in /home/vagrant/.composer/vendor/youzan/zan-installer/src/Installer.php on line 302

Warning: file_get_contents(/vagrant、/vagrant/test/init/app.php): failed to open stream: No such file or directory in /home/vagrant/.composer/vendor/youzan/zan-installer/src/Installer.php on line 302
Set {{APP_NAME}} fail :(

**Comment by daxiong123** [comment]
![image](https://cloud.githubusercontent.com/assets/2648157/17963135/a332e240-6ae6-11e6-9739-5c4e191dabd5.png)

另外发现一个问题就是 新建项目后 tests目录下的bootstrap文件中的$appName没有引号

**Comment by agalwood** [comment]
你PR的改法不对的，不能直接去掉新建目录的，用你的改法运行结果如下：

``` bash
   __    __                                          
  /\ \  /\ \                                         
  \ `\`\\/'/ ___   __  __  ____      __      ___     
   `\ `\ /' / __`\/\ \/\ \/\_ ,`\  /'__`\  /' _ `\   
     `\ \ \/\ \L\ \ \ \_\ \/_/  /_/\ \L\.\_/\ \/\ \  
       \ \_\ \____/\ \____/ /\____\ \__/.\_\ \_\ \_\ 
        \/_/\/___/  \/___/  \/____/\/__/\/_/\/_/\/_/ 
Create a new ZanPhp application.
Which type application would you create? (use <space> to select)
❯ ● HTTP                                                                                                                                                                                              
  ○ TCP                                                                                                                                                                                               
Your application name: (ex: zanphp-demo) demo4
Please input a output directory: /data/test
Your composer name: (ex: zanphp/zanhttp) 
Use composer name: zanphp/zanhttp
Your application namespace: (ex: Com\Youzan\ZanHttpDemo\) 
Use default namespace: Com\Youzan\ZanHttpDemo\
Downloading the source code archive ...
Extracting archive ...
PHP Notice:  Undefined variable: dir in /Users/xanaduv/Sites/open/zan-installer/src/Installer.php on line 287

Notice: Undefined variable: dir in /Users/xanaduv/Sites/open/zan-installer/src/Installer.php on line 287
PHP Warning:  chmod(): No such file or directory in /Users/xanaduv/Sites/open/zan-installer/src/Installer.php on line 287

Warning: chmod(): No such file or directory in /Users/xanaduv/Sites/open/zan-installer/src/Installer.php on line 287
Congratulations, your application has been generated to the following directory.
/data/test/demo4/
See /data/test/demo4/README.md for information on how to run.
Composer installing...
Loading composer repositories with package information                                                                                          Updating dependencies (including require-dev)           - Installing zanphp/zan (dev-master db4838c)
    Cloning db4838ca28c1f54c5cfc1ad9a3452d8aa920adc1

Writing lock file
Generating autoload files
```

**Comment by agalwood** [comment]
test 的$appName的确少了引号，已经修复了

> 另外发现一个问题就是 新建项目后 tests目录下的bootstrap文件中的$appName没有引号

**Comment by agalwood** [comment]
![image](https://cloud.githubusercontent.com/assets/1032175/17963459/45473f80-6ae8-11e6-888a-356533568fe7.png)

**Comment by agalwood** [comment]
你的rename问题，我还得再查下

**Comment by daxiong123** [comment]
![image](https://cloud.githubusercontent.com/assets/2648157/17963598/e1e20226-6ae8-11e6-8a6a-d96fc32cd99e.png)


个人觉得可以不创建目录 直接rename 然后重新chmod就可以了

**Comment by daxiong123** [comment]
![image](https://cloud.githubusercontent.com/assets/2648157/17963658/39559f22-6ae9-11e6-9d55-6f7389347cac.png)

但是去掉创建目录 直接rename我这边就可以了

**Comment by agalwood** [comment]
不一定，目标目录如果连父级都不存在的时候就会扑街的

``` bash
/data  ᐅ ls
www
/data/www  ᐅ ls
demo  demo3
```

``` php
<?php
    $oldDir = '/data/www/demo3';
    $newDir = '/data/www2/demo3';
    rename($oldDir, $newDir);
?>
```

PHP Warning:  rename(/data/www/demo3,/data/www2/demo3): No such file or directory in /private/var/folders/lf/9r7s62qj2598lq6hyk7d9ky80000gn/T/CodeRunner/Untitled.php on line 4

Warning: rename(/data/www/demo3,/data/www2/demo3): No such file or directory in /private/var/folders/lf/9r7s62qj2598lq6hyk7d9ky80000gn/T/CodeRunner/Untitled.php on line 4

**Comment by daxiong123** [comment]
这个倒是

**Comment by daxiong123** [comment]
可以创建目录截止到目标目录的上级目录 然后目标目录使用rename

**Comment by agalwood** [comment]
主要是我开发的时候没有碰到你的情况，因为我使用的时候是OK的，你看我上面发的图，就是目录不存在，创建后再rename的

**Comment by daxiong123** [comment]
关键是我现在使用上确实出现这个问题了 好尴尬啊

**Comment by agalwood** [comment]
－。－我晚上再排查下吧

**Comment by daxiong123** [comment]
好的 我现在临时改一下吧 期待你的好消息 ：）

**Comment by agalwood** [comment]
@daxiong123 拉下代码，切到 [hotfix/fix_issue_4](https://github.com/youzan/zan-installer/tree/hotfix/fix_issue_4) 分支下试下：P

**Comment by agalwood** [comment]
fixed at v1.0.9，可以更新了～
