### ISSUE TITLE
when I install zan, OpenSSL Error

### ISSUE THREAD

**Issue by huanmyu** [youzan/zan-installer#6]
ubuntu@ubuntu-xenial:~/php-7.1.6$ zan
   __    __                                          
  /\ \  /\ \                                         
  \ `\`\\/'/ ___   __  __  ____      __      ___     
   `\ `\ /' / __`\/\ \/\ \/\_ ,`\  /'__`\  /' _ `\   
     `\ \ \/\ \L\ \ \ \_\ \/_/  /_/\ \L\.\_/\ \/\ \  
       \ \_\ \____/\ \____/ /\____\ \__/.\_\ \_\ \_\ 
        \/_/\/___/  \/___/  \/____/\/__/\/_/\/_/\/_/ 
Create a new ZanPhp application.
Which type application would you create? (use <space> to select)
❯ ● HTTP                                                                      
  ○ TCP                                                                       
Your application name: (ex: zanphp-demo) 
Use default application name: zanphp-demo
Please input a output directory: zanphp-http
Your composer name: (ex: zanphp/zanhttp) 
Use composer name: zanphp/zanhttp
Your application namespace: (ex: Com\Youzan\ZanHttpDemo\) 
Use default namespace: Com\Youzan\ZanHttpDemo\
Downloading the source code archive ...
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319

Warning: file_get_contents(): Failed to enable crypto in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319
PHP Warning:  file_get_contents(https://codeload.github.com/youzan/zanhttp-boilerplate/zip/master): failed to open stream: operation failed in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319

Warning: file_get_contents(https://codeload.github.com/youzan/zanhttp-boilerplate/zip/master): failed to open stream: operation failed in /home/ubuntu/.config/composer/vendor/youzan/zan-installer/src/Installer.php on line 319
ERROR: Download code fail :(

**Comment by huanmyu** [comment]
php version 7.1.6
openssl version 1.0.2l

**Comment by xhjcehust** [comment]
Maybe something go wrong with your CA certificate, Then we omit CA verify when visiting https.
git pull this repository and retry, thanks

**Comment by huanmyu** [comment]
ok

**Comment by huanmyu** [comment]
I try pull this repository, have resolve.
